---
- name: Converge
  hosts: all



#  pre_tasks:
#    - name: "Testing an ansible client initial server setup"
#      apt: update_cache=true cache_valid_time=3600
#      when: ansible_os_family == 'Debian'

- name: Running main.yml
  import_playbook: ../../main.yml
